Certainly! Here is an example Ansible playbook that deploys an application with two pods, utilizing a secret, configmap, services, and routes in an OpenShift cluster:

```yaml
---
- name: Deploy application
  hosts: localhost
  gather_facts: false
  vars:
    app_name: myapp
    app_image: your-app-image:latest

  tasks:
    - name: Create Secret
      k8s:
        api_version: v1
        kind: Secret
        metadata:
          name: app-secret
        data:
          username: "{{ lookup('env', 'APP_USERNAME') }}"
          password: "{{ lookup('env', 'APP_PASSWORD') }}"
        type: Opaque

    - name: Create ConfigMap
      k8s:
        api_version: v1
        kind: ConfigMap
        metadata:
          name: app-config
        data:
          app-config.properties: |
            key1: value1
            key2: value2

    - name: Deploy Pods
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: "{{ app_name }}-pod-1"
          spec:
            containers:
              - name: app-container
                image: "{{ app_image }}"
                env:
                  - name: APP_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: app-secret
                        key: username
                  - name: APP_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: app-secret
                        key: password

    - name: Create Service
      k8s:
        api_version: v1
        kind: Service
        metadata:
          name: "{{ app_name }}-service"
        spec:
          selector:
            name: "{{ app_name }}-pod-1"
          ports:
            - port: 80
              targetPort: 8080

    - name: Create Route
      k8s:
        api_version: route.openshift.io/v1
        kind: Route
        metadata:
          name: "{{ app_name }}-route"
        spec:
          to:
            kind: Service
            name: "{{ app_name }}-service"
          port:
            targetPort: 8080
```

This playbook deploys an application with two pods using a secret (`app-secret`) for storing sensitive data, a configmap (`app-config`) for storing configuration settings, a service (`myapp-service`) to expose the pods, and a route (`myapp-route`) to expose the service externally.

To execute this playbook:

1. Replace `your-app-image:latest` with the actual image you want to use for the application.
2. Set the environment variables `APP_USERNAME` and `APP_PASSWORD` with the desired values for the secret.
3. Save this playbook to a file (e.g., `deploy.yaml`).
4. Run the playbook using the `ansible-playbook` command:

```shell
ansible-playbook -i inventory.ini deploy.yaml
```

Note that you need to have Ansible installed, along with the `openshift` Python package. Please ensure you have the necessary permissions to create the resources in the OpenShift cluster.

Feel free to adjust the playbook according to your specific requirements for the secret, configmap, services, and routes.

I hope this helps you deploy an application with secret, configmap, services, and routes using Ansible in an OpenShift cluster!