To use Ansible to get the secrets in OpenShift, you can use the `oc` command line tool and run it through the `ansible.builtin.command` module. Here's an example playbook:

```yaml
- name: Get Secrets in OpenShift
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run oc command to get secrets
      ansible.builtin.command: oc get secrets -o json
      register: oc_output
    - name: Parse json output
      ansible.builtin.set_fact:
        secrets_list: "{{ oc_output.stdout | from_json }}"
    - name: Print secret names
      ansible.builtin.debug:
        msg: "{{ item.metadata.name }}"
      with_items: "{{ secrets_list.items }}"
```

In this playbook, we first run the `oc get secrets -o json` command using the `ansible.builtin.command` module and register the output in the `oc_output` variable. We then use the `set_fact` module to parse the JSON output into the `secrets_list` variable.

Finally, we iterate over the `secrets_list.items` and print the names of each secret using the `debug` module.

You can run this playbook using the `ansible-playbook` command:

```
ansible-playbook get_secrets.yaml
```

This playbook will run the `oc get secrets` command and display the names of all the secrets in the console.