To use Ansible to get the Persistent Volume Claims (PVCs) in OpenShift, you can use the `oc` command line tool and run it through the `ansible.builtin.command` module. Here's an example playbook:

```yaml
- name: Get PVCs in OpenShift
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run oc command to get PVCs
      ansible.builtin.command: oc get pvc -o json
      register: oc_output
    - name: Parse json output
      ansible.builtin.set_fact:
        pvc_list: "{{ oc_output.stdout | from_json }}"
    - name: Print PVC names
      ansible.builtin.debug:
        msg: "{{ item.metadata.name }}"
      with_items: "{{ pvc_list.items }}"
```

In this playbook, we first run the `oc get pvc -o json` command using the `ansible.builtin.command` module and register the output in the `oc_output` variable. We then use the `set_fact` module to parse the JSON output into the `pvc_list` variable.

Finally, we iterate over the `pvc_list.items` and print the names of each PVC using the `debug` module.

You can run this playbook using the `ansible-playbook` command:

```
ansible-playbook get_pvc.yaml
```

This playbook will run the `oc get pvc` command and display the names of all the PVCs in the console.